---
- hosts: all
  name: User configuration
  roles:
    - kewlfft.aur
  remote_user: "{{ user }}"

  tasks:
    - name: Install config files
      copy:
        src: "{{ item }}"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
      with_fileglob:
        - cfg/home/.*

    - name: Install .config directory
      copy:
        src: cfg/home/.config/
        dest: "/home/{{ user }}/.config"
        owner: "{{ user }}"
        mode: '700'

    - include: tasks/polybar_config.yml
    - include: tasks/install_vim.yml
    - include: tasks/oh_my_zsh.yml
    - include: tasks/user_programs.yml
    - include: tasks/keepass.yml
