- name: Ensure xorg utils are installed
  pacman:
    name:
      - xorg
      - xorg-xinit

- name: Ensure i3-gaps is installed
  pacman:
    name:
      i3-gaps

- name: Set X11 configuration
  copy:
    src: cfg/etc/X11/
    dest: /etc/X11/
