- name: Install oh my zsh
  become: yes
  block:
    - name: Install zsh and wget
      pacman:
        name:
          - zsh
          - curl

    - name: Install oh my zsh
      shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

    - name: Change user shell
      user:
        name: "{{ user }}"
        shell: /usr/bin/zsh

    - name: Set zsh config file
      template:
        src: templates/zshrc.j2
        dest: "/home/{{ user }}/.zshrc"
