- name: Install oh my zsh
  block:
    - name: Install zsh and wget
      become: yes
      pacman:
        name:
          - zsh
          - wget

    - name: Change user shell
      become: yes
      user:
        name: "{{ user }}"
        shell: /usr/bin/zsh

    - name: Install oh my zsh
      shell: 'sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"'
      async: 30
      poll: 0

    - name: Set zsh config file
      template:
        src: templates/zshrc.j2
        dest: "/home/{{ user }}/.zshrc"
