- name: Rank mirrors
  block:
    - name: Ensure pacman-contrib is installed
      pacman:
        name: pacman-contrib

    - name: Create backup of mirrorlist
      copy:
        remote_src: yes
        src: /etc/pacman.d/mirrorlist
        dest: /etc/pacman.d/mirrorlist.backup

    - name: Uncomment every server  in mirrorlist
      replace:
        path: /etc/pacman.d/mirrorlist.backup
        regexp: ^#Server
        replace: Server

    - name: Start sorting of mirrors
      shell: /usr/bin/rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist
